# Basic `dependabot.yml` file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directories:
      - "/benchmarks/nodejs-shopping-chart"
      - "/benchmarks/nodejs-todo"
    schedule:
      interval: "weekly"
